version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: uv
    directory: /backend
    schedule:
      interval: weekly
  - package-ecosystem: uv
    directory: /edge
    schedule:
      interval: weekly
  - package-ecosystem: uv
    directory: /packages/tekton-conventions
    schedule:
      interval: weekly
  - package-ecosystem: pnpm
    directory: /frontend
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
